os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11.3

cache:
  directories:
    - ${HOME}/.swiftenv/

install:
  - eval "$(cat install_swift.sh)"
  - bundle install

script:
  - swift build
  - bundle exec ruby run.rb